apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: secret-volume 
          mountPath: /tmp/secretVolume
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
     