apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs: # Definição do NFS
    path: /tmp/nfs-server
    readOnly: false
    server: host.minikube.internal


    