apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-application
          image: azold6/jenkins-with-spring:jenkins-spring-pipeline-49
  strategy: ######## Configuração de atualização de Pods
    type: RollingUpdate 