apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole ################# Informando o cluster-role
  name: cluster-admin ############### a ser bindado
subjects:
- kind: ServiceAccount ############## Informando o service-account
  name: admin-user ################## a ser bindado
  namespace: kube-system ############ e seu namespace