apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: busybox
      image: busybox
      envFrom: ###################### Podemos puxar todas as envs
        - configMapRef:             # contidas em um ConfigMap 
            name: my-configmap ###### de uma sรณ vez com o envFrom