apiVersion: v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-application
          image: azold6/jenkins-with-spring:jenkins-spring-pipeline-49
          env:
            - NAME: ENV_HELLO
              valueFrom:
                configMapKeyRef:
                  name: my-configmap # Name of my ConfigMap
                  key: hello # Key name inside my ConfigMap