apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    containers:
      - name: spring-application
        image: azold6/jenkins-with-spring:jenkins-spring-pipeline-49
        env:
          - name: MY_ENV_1
            value: 'hello'
          - name: MY_ENV_2
            value: 'world'