apiVersion: v1
kind: Service
metadata:
  name: fileupload-svc
spec:
  selector:
    app: fileupload
  ports:
    - port: 8080
      targetPort: 8080
      protocol: 'TCP'
  type: LoadBalancer
      
    