apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: alex
spec:
  selector:
    app: my-app
  ports:
    - port: 8081
      targetPort: 8081
      protocol: 'TCP'
  type: LoadBalancer
  sessionAffinity: ClientIP ## Definição do sessionAffinity